services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - /app/Backend/node_modules
    depends_on:
      - ai-backend

  ai-backend:
    build:
      context: ./AI
      dockerfile: Dockerfile
    env_file:
      - ./AI/.env
    ports:
      - '8000:8000'
    volumes:
      - ./AI:/app
